### ISSUE TITLE
Fragment arguments with arguments other than a scalar breaks

### ISSUE THREAD

**Issue by SeppahBaws** [HoudiniGraphql/houdini#1165]
### Describe the bug

When using fragment arguments, if I pass in an argument like this, I get a `Maximum call stack size exceeded` error in the sveltekit e2e testing project.

```html
<script lang="ts">
  import { graphql, fragment } from '$houdini';

  $: queryResult = graphql(`
    query MyQuery {
      ...MyFragment @with(filter: { name: "Bruce" })
    }
  `);

  $: fragmentResult = fragment(
    $queryResult.data ?? null,
    graphql(`
      fragment MyFragment on Query @arguments(filter: { type: "UserNameFilter!" }) {
        userSearch(snapshot: "some-user", filter: $filter) {
          id
          name
        }
      }
    `)
  );
</script>
```

However, either of these two alternatives work:
1. query argument
```gql
query MyQuery($filter: UserNameFilter!) {
  ...MyFragment @with(filter: $filter)
}
```
2. different `@arguments` type
```gql
query MyQuery {
  ...MyFragment @with(name: "Bruce")
}
fragment MyFragment on Query @arguments(name: { type: "String!" }) {
  userSearch(snapshot: "some-user", filter: { name: $name }) {
    id
    name
  }
}
```

I can work around it with either two alternatives, but for my current use case I would prefer to be able to simply pass in the entire `UserNameFilter` input object, as that would make my fragment more flexible.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Create a new file in the e2e/kit project: `src/routes/test/+page.svelte`
2. Paste the first code snippet from above in this route
3. Run `houdini generate` and see the "Maximum call stack size exceeded" error message

**Comment by SeppahBaws** [comment]
here's the stack trace:
```
🎩 Generating runtime...
❌ Maximum call stack size exceeded
    at ObjectType2.check (file:///F:/dev/houdini/packages/houdini/build/cmd-esm/index.js:29755:45)
    at addParam (file:///F:/dev/houdini/packages/houdini/build/cmd-esm/index.js:30072:23)
    at file:///F:/dev/houdini/packages/houdini/build/cmd-esm/index.js:30095:15
    at Array.forEach (<anonymous>)
    at Object.builder [as stringLiteral] (file:///F:/dev/houdini/packages/houdini/build/cmd-esm/index.js:30094:42)
    at file:///F:/dev/houdini/packages/houdini/build/cmd-esm/index.js:70112:53
    at Array.map (<anonymous>)
    at serializeValue (file:///F:/dev/houdini/packages/houdini/build/cmd-esm/index.js:70111:83)
    at file:///F:/dev/houdini/packages/houdini/build/cmd-esm/index.js:70112:73
    at Array.map (<anonymous>)
```
