### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by darktempla** [HoudiniGraphql/houdini#1242]
### Describe the bug

I have only just attempted to use Houdini so am relatively new to it.
So it is possible I am doing something wrong.
Any guidance would be appreciated.

The issue/bug is after fetching the data from the GraphQL endpoint it appears it fails to convert it into a strongly typed object(s) that reflects the schema downloaded during houdini project setup. 

_NOTE: the schema  has not change since I first generated the schema file._ 

The work around is to use the serverside only approach which means I loose ALOT of the reasons I would use Houdini in the first place. 

### Houdini Version
```
"houdini": "^1.2.34",
"houdini-svelte": "^1.2.34"
```
### Severity

serious, but I can work around it

### Schema
Generated during `npx houdini@latest init` command
[schema.graphql.txt](https://github.com/HoudiniGraphql/houdini/files/13691462/schema.graphql.txt)

### Query (+page.gql)
```
query StockSymbols {
    allSummaries {
        totalCount
        nodes {
	    symbol
        }
    }
}
```
### Page (+page.svelte)
```html
<script lang="ts">
	/* @type { import('./$houdini').PageData } */
	export let data;
	// $: ({ StockSymbols } = data);
</script>

<div>
	<a href="/">back</a>
</div>

<h3>Houdini GraphQL (file based example)</h3>

<div>
  {JSON.stringify(data)}
</div>
```
### Stringfy Data
```js
{"__houdini__session__":{"graphQLAuth":"REDACTED},"StockSymbols":{"variables":false,"kind":"HoudiniQuery","loadPending":false,"storeName":"StockSymbolsStore"}}
```

### Error
If I change the `+page.svelte` page to this I get the following error.
Basically I am just attempt to grab the data from the store `$: ({ StockSymbols } = data)`

```html
<script lang="ts">
	/* @type { import('./$houdini').PageData } */
	export let data;
	$: ({ StockSymbols } = data);
</script>

<div>
	<a href="/">back</a>
</div>

<h3>Houdini GraphQL (file based example)</h3>

{#each StockSymbols.data.allSummaries.nodes as stockSummary}
<ul>
  <li>{stockSummary.symbol}</li>
  </ul>
{/each}
```
ERROR:
```
TypeError: Cannot read properties of undefined (reading 'allSummaries')
    at /Users/darktempla/Code/Projects/Sentimental/source/houdini-test/src/routes/houdini-file/+page.svelte:28:5
    at Object.$$render (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/node_modules/.pnpm/svelte@4.2.8/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.default (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/.svelte-kit/generated/root.svelte:45:41)
    at eval (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/src/routes/+layout.svelte:25:100)
    at Object.$$render (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/node_modules/.pnpm/svelte@4.2.8/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at /Users/darktempla/Code/Projects/Sentimental/source/houdini-test/.svelte-kit/generated/root.svelte:44:40
    at $$render (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/node_modules/.pnpm/svelte@4.2.8/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.render (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/node_modules/.pnpm/svelte@4.2.8/node_modules/svelte/src/runtime/internal/ssr.js:164:17)
    at Module.render_response (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/node_modules/.pnpm/@sveltejs+kit@1.30.1_svelte@4.2.8_vite@4.5.1/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:170:29)
    at async Module.render_page (/Users/darktempla/Code/Projects/Sentimental/source/houdini-test/node_modules/.pnpm/@sveltejs+kit@1.30.1_svelte@4.2.8_vite@4.5.1/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:286:10)
```

### Server Side Only
If I follow your server side only example it works no worries which gives me confidence the client and data being returned is fine it seems when Houdini attempts to convert it into the model is where the issue presents itself. 

```ts
import { StockSymbolsStore } from '$houdini';

// /* @type { import('./$houdini').PageLoad } */
export const load = async (event) => {
  const myQuery = new StockSymbolsStore();
  const { data } = await myQuery.fetch({ event });
  console.log('------ BEGIN: SEVER SIDE DATA ------');
  console.log(data);
  console.log('------ END: SEVER SIDE DATA ------');
  return {
    stock: data
  }
}
```
Template
```html
<script lang="ts">
   export let data;
  $: ({ stock } = data);
</script>

<div>
	<a href="/">back</a>
</div>

<h3>Houdini GraphQL (server only example)</h3>

<div>
  Result count: {stock?.allSummaries?.totalCount}
</div>

{#each stock.allSummaries.nodes as stockSummary}
<ul>
  <li>{stockSummary.symbol}</li>
</ul>
{/each}
```
Data returned server side in console out
```js
{
  allSummaries: {
    totalCount: 89,
    nodes: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object]
    ]
  }
}
```

**Comment by jycouet** [comment]
I think that you can try like this: 
```svelte
{#each $StockSymbols.data?.allSummaries?.nodes ?? [] as stockSummary}
```

1/ You need to look at the store values (starting with a $)
2/ You need to manage if you have no data (this is one way)

Maybe you can log with `{ JSON.Stringify($StockSymbols) }` to see states changing (loading & co) to help you figure out what it's doing.

Overall, thank you very much for all details. Let us know if it helps 👍

**Comment by darktempla** [comment]
@jycouet - thanks heaps for the prompt reply. No worries RE: details I work in IT and appreciate when someone gives me all the details to assist me in helping. 

I now see the error of my ways :) thanks.

BTW massive fan of what Houdini has done in its approach to align with SvelteKit like paradigms.

For people following along at home. Looks like I had two issues:
1. No `$` sign as highlighted. 
1. I was not allowing for the data still being fetched when the view initially loaded

For point 2, I could use the default value `?? [ ]` as suggested. Alternatively no default value and the following worked as well.
 
```svelte
{#if $StockSymbols.fetching}
  <div>Loading...</div>
{:else}
  {#each $StockSymbols.data.allSummaries.nodes as stockSummary}
  <ul>
    <li>{stockSummary.symbol}</li>
  </ul>
  {/each}
{/if}
```
