### ISSUE TITLE
Houdini Vite plugin doesn't support Vite 6

### ISSUE THREAD

**Issue by Rudedog9d** [HoudiniGraphql/houdini#1401]
### Describe the bug

Trying to run the vite dev server with houdini on Svelte 5 throws errors regarding missing files `+layout.js` / `+layout.server.js` / `+page.js`. 

```
4:38:30 PM [vite] (ssr) Error when evaluating SSR module /src/routes/+layout.js:
|- Error: [vite] cannot find entry point module '/src/routes/+layout.js'.
    at fetchModule (file:///home/bdavis/Dev/svelte-houdini-error/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:51161:13)
    at async handleInvoke (file:///home/bdavis/Dev/svelte-houdini-error/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:43945:22)
    at async EventEmitter.listenerForInvokeHandler (file:///home/bdavis/Dev/svelte-houdini-error/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:44018:19)
```

This appears to be an issue with extra files being added to `.svelte-kt/types/route_meta_data.json`. Interestingly, the issue doesn't appear when running:

- `svelte-kit sync && houdini generate`
- `vite build`
- `vite preview`

I've tried changing around a few configurations, but I'm unable to determine what is the problem. Adding a `+layout.js` file just moves the error to

```
Error: [vite] cannot find entry point module '/src/routes/+layout.server.js'.
```

Then it eventually expects `+page.js`. Adding in all the files it wants _does eventually work_, but they shouldn't be required. Right? I'm not crazy?

I've included a repo with a fresh build of svelte5 and houdini as per the setup instructions/commands. I know it's not the _simplest repro_ at 26 files, but I wasn't sure a better way. I made sure to include repo steps in the README and add git commits at significant steps.

This seems like it must be an issue with the houdini vite plugin. **Commenting out the `houdini()` plugin in `vite.config.ts` DOES fix the problem** (granted, houdini doesn't work.)

### Reproduction

https://github.com/Rudedog9d/houdini-svelte-error

**Comment by Rudedog9d** [comment]
After some more investigation, using vite version 5.x looks to be fine. So I guess this is a vite v6 issue. Atleast that's an easy work around :) 

The following change (combined with `rm -r node_modules package-lock.json` and `npm i`) works:

```diff
         "@sveltejs/adapter-auto": "^3.0.0",
         "@sveltejs/adapter-node": "^5.2.9",
         "@sveltejs/kit": "^2.9.0",
-        "@sveltejs/vite-plugin-svelte": "^5.0.0",
+        "@sveltejs/vite-plugin-svelte": "^4.0.0",
         "svelte": "^5.0.0",
         "svelte-check": "^4.0.0",
         "typescript": "^5.0.0",
-        "vite": "^6.0.0",
+        "vite": ">5.0.0 <6.0.0",
         "houdini": "^1.3.1",
         "houdini-svelte": "^2.0.1"
     }
```

**Comment by moonmeister** [comment]
I've got everything updated and this error is still occurring 

```
@eslint/js 9.17.0                   eslint 9.17.0                       houdini-svelte 2.1.0                prettier-plugin-svelte 3.3.2        typescript-eslint 8.19.0            
@graphql-inspector/cli 5.0.8        eslint-config-prettier 9.1.0        postcss 8.4.49                      svelte 5.16.0                       vite 6.0.6                          
@sveltejs/kit 2.15.1                eslint-plugin-svelte 2.46.1         postcss-custom-media 11.0.5         svelte-check 4.1.1                  
@sveltejs/vite-plugin-svelte 5.0.3  globals 15.14.0                     postcss-load-config 6.0.1           svelte-preprocess 6.0.3             
@types/gtag.js 0.0.20               graphql 16.10.0                     postcss-nesting 13.0.1              tslib 2.8.1                         
autoprefixer 10.4.20                houdini 1.4.0                       prettier 3.4.2                      typescript 5.7.2         
```

**Comment by SeppahBaws** [comment]
@moonmeister Thanks for reporting this. Someone on Discord also already mentioned it can still give errors, but I haven't had the time yet to look into it due to the holidays. 

I'll try to look into it in the coming few days...

**Comment by AlecAivazis** [comment]
Hey everyone, I was able to get passed the error and run the e2e test suite. Can someone test the fix to see if it works for them too? Thanks!

**Comment by Serator** [comment]
Hey @AlecAivazis 👋. I'm still encountering an error when trying to upgrade to Vite 6.

<img width="605" alt="Image" src="https://github.com/user-attachments/assets/6177b5a7-effa-4229-bb0f-611d672eed63" />

<img width="776" alt="Image" src="https://github.com/user-attachments/assets/30498b1a-9459-48c9-9c81-7fbf6740a2b9" />

https://github.com/search?q=repo%3AHoudiniGraphql%2Fhoudini+5.3.3&type=code

**Comment by SeppahBaws** [comment]
Hey @Serator, thanks for letting us know! Seems like we missed something in between the peer dependencies and vite 6 PRs. Should be fixed with #1430!
