### ISSUE TITLE
Maximum call stack size exceeded when @include in sub fields

### ISSUE THREAD

**Issue by doukai** [HoudiniGraphql/houdini#1406]
### Describe the bug

When @include exists in realm field, an exception is thrown

```
query Query_group_agg($id: StringExpression $name: StringExpression  $include_id: Boolean = false $include_name: Boolean = false $include_realm: Boolean = false $include_realm_nameCount: Boolean = false $include_realm_nameMax: Boolean = false $include_realm_nameMin: Boolean = false ) {
  group(id: $id name: $name) {
    id @include(if: $include_id)
    name @include(if: $include_name)
    realm @include(if: $include_realm) {
      nameCount @include(if: $include_realm_nameCount)
      nameMax @include(if: $include_realm_nameMax)
      nameMin @include(if: $include_realm_nameMin)
    }
  }
}
```

```
Maximum call stack size exceeded
```
After eliminating @include in realm filed, success

```
query Query_group_agg($id: StringExpression $name: StringExpression  $include_id: Boolean = false $include_name: Boolean = false $include_realm: Boolean = false $include_realm_nameCount: Boolean = false $include_realm_nameMax: Boolean = false $include_realm_nameMin: Boolean = false ) {
  group(id: $id name: $name) {
    id @include(if: $include_id)
    name @include(if: $include_name)
    realm @include(if: $include_realm) {
      nameCount
      nameMax
      nameMin
    }
  }
}
```

Any good ideas? Thanks

**Comment by AlecAivazis** [comment]
I tried to reproduce this on the houdini test suite with this query and was able to generate the necessary artifact:

```
query UserWithAvatar(
				$includeUser: Boolean! = false, 
				$includeFriends: Boolean! = false, 
				$includeCat: Boolean! = false, 
				$includeID: Boolean! = false, 
				$includeName: Boolean! = false,
				$includeOwner: Boolean! = false
			) {
				user @include(if: $includeUser) {
					friends @include(if: $includeFriends) { 
						cats @include(if: $includeCat) { 
							id @include(if: $includeID)
							name @include(if: $includeName)
							owner @include(if: $includeOwner) { 
								name @include(if: $includeName)
							}
						}
					}
				}
			}
```

Can you open up a reproduction somewhere I can take a look?

**Comment by AlecAivazis** [comment]
Going to close this since it's gone a bit stale. happy to reopen it if you can put together a reproduction I can take a look at

**Comment by doukai** [comment]
> Going to close this since it's gone a bit stale. happy to reopen it if you can put together a reproduction I can take a look at

Sorry, due to work reasons, the problem disappeared after I changed the development environment. If I encounter it again, I will make it into a demo and check the problem again.

**Comment by doukai** [comment]
> I tried to reproduce this on the houdini test suite with this query and was able to generate the necessary artifact:
> 
> ```graphql
> query UserWithAvatar(
> 	$includeUser: Boolean! = false, 
> 	$includeFriends: Boolean! = false, 
> 	$includeCat: Boolean! = false, 
> 	$includeID: Boolean! = false, 
> 	$includeName: Boolean! = false,
> 	$includeOwner: Boolean! = false
> ) {
> 	user @include(if: $includeUser) {
> 		friends @include(if: $includeFriends) { 
> 			cats @include(if: $includeCat) { 
> 				id @include(if: $includeID)
> 				name @include(if: $includeName)
> 				owner @include(if: $includeOwner) { 
> 					name @include(if: $includeName)
> 				}
> 			}
> 		}
> 	}
> }
> ```
> 
> Can you open up a reproduction somewhere I can take a look? Or if you could provide the full stack trace, it'd help hunt down the callsite

@AlecAivazis I wrote a test case

[https://github.com/doukai/houdini-issues-1406](url)

 query file: src/graphql/Query_group_includes.gql

which would trigger an exception

`
RangeError: Maximum call stack size exceeded
    at Map.set (<anonymous>)
    at as (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71328:7)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71352:16)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71380:38)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71380:38)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71380:38)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71380:38)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71380:38)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71380:38)
    at pair (file:///Users/doukai/houdini-issues-1406/node_modules/houdini/build/vite-esm/index.js:71380:38)
`
