### ISSUE TITLE
Error: config.kit.vite has been removed — use vite.config.js instead

### ISSUE THREAD

**Issue by kris-re** [HoudiniGraphql/houdini#396]
I followed your guide on setting up a project: https://www.houdinigraphql.com/guides/setting-up-your-project

Both Houdini and SvelteKit are freshly installed. After trying to launch the dev server, said error displays.

Removing following lines from `svelte.config.js` solves it, but I cannot use Houdini. 😄 

```js
		vite: {
			resolve: {
				alias: {
					$houdini: path.resolve('.', '$houdini')
				}
			},
			server: {
				fs: {
					allow: ['.']
				}
			}
		}
```

Has this something to do with your warning on SvelteKit version `1.0.0-next.356`? I have `1.0.0-next.367` installed. Doesn't look like a problem with "resolving query fetches" though.

Complete error log:

```
error when starting dev server:
Error: config.kit.vite has been removed — use vite.config.js instead
    at file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/chunks/error.js:563:10
    at file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/chunks/error.js:455:43
    at file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/chunks/error.js:441:18
    at file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/chunks/error.js:441:18
    at validate_config (file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/chunks/error.js:647:9)
    at process_config (file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/chunks/error.js:624:20)
    at load_config (file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/chunks/error.js:616:9)
    at async Object.config (file:///Users/crstn/svelte/shops/node_modules/@sveltejs/kit/dist/vite.js:2896:20)
    at async resolveConfig (/Users/crstn/svelte/shops/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61491:25)
    at async createServer (/Users/crstn/svelte/shops/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:60105:20)
```

**Comment by AlecAivazis** [comment]
Ah yea it's not the exact same bug but its also related to a [recent breaking change](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next359). I'm in the process of updating the getting started guide and `init` commands right now. 

The actual fetching bug (https://github.com/HoudiniGraphql/houdini/issues/374) has been fixed.

You should be set if you just copy the body of the `vite` object into your `vite.config.js` file

**Comment by kris-re** [comment]
Thanks, I tried that but a bunch of other errors pop up. After solving one problem, another appears.

Current issue:

```
Cannot read properties of null (reading 'products')
```

Component:

```svelte
<script>
	import { query, graphql } from '$houdini';

	const { data } = query(graphql`
		query Products {
			products {
				edges {
					node {
						name
					}
				}
			}
		}
	`);
</script>

<ul>
	{#each $data.products.edges as product}
		<li>{product.node.name}</li>
	{/each}
</ul>
```

Query is working in GraphQL IDE and `houdini generate` was executed to solve a problem with missing artifacts.

Maybe I wait for the updated guide.

**Comment by AlecAivazis** [comment]
Looks like you got passed the config issues the update would help you with. I think you're running into something different. Can you give me some more info about your component? Is this a sveltekit project? if so, what's the filepath of the component? I suspect you are running into a loading state where $data is set to null before the query resolvers

**Comment by AlecAivazis** [comment]
I've updated the Setup guide but I'm going to change the title and leave this issue open while we try to figure out what's going on in your project 👍

**Comment by kris-re** [comment]
Thank you for the quick responses.

Yes, it is a SvelteKit project. I updated the config based on your updated guide. All relevant files:

**houdini.config.js**
```js
/** @type {import('houdini').ConfigFile} */
const config = {
	schemaPath: './schema.graphql',
	sourceGlob: 'src/**/*.{svelte,gql,graphql}',
	module: 'esm',
	framework: 'kit',
	apiUrl: 'https://api.endpoint.com/graphql'
};

export default config;
```

**svelte.config.js**
```js
import adapter from '@sveltejs/adapter-auto';
import houdini from 'houdini/preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [houdini()],

	kit: {
		adapter: adapter(),
		alias: {
			$houdini: './$houdini'
		}
	}
};

export default config;
```

**vite.config.js**
```js
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()],
	server: {
		fs: {
			allow: ['.']
		}
	}
};

export default config;
```

**src/houdiniClient.js**
```js
import { HoudiniClient } from '$houdini/runtime'

async function fetchQuery({ fetch, session, text = '', variables = {} }) {
	const result = await fetch('https://api.endpoint.com/graphql', { // why is this hardcoded?
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({
			query: text,
			variables,
		}),
	})
	return await result.json()
}

export default new HoudiniClient(fetchQuery)
```

**src/routes/__layout.svelte**
```svelte
<script context="module">
	import houdiniClient from '../houdiniClient'; // not '../client'

	houdiniClient.init();
</script>

<slot />
```

**src/routes/index.svelte**
```svelte
<script context="module">
	import Products from '$lib/components/Products.svelte'; // I like the components inside $lib
</script>

<Products />
```

**lib/components/Products.svelte**
Components placed outside of `lib` have the same effect.
```svelte
<script>
	import { query, graphql } from '$houdini';

	const { data } = query(graphql`
		query Products {
			products {
				edges {
					node {
						name
					}
				}
			}
		}
	`);
</script>

<ul>
	{#each $data.products.edges as product}
		<li>{product.node.name}</li>
	{/each}
</ul>
```

**Comment by AlecAivazis** [comment]
Since your query lives in a non-route component, the query fires when your component mounts which means at first, there is no data hence your error. I think you can address this with 

```svelte
<script>
	import { query, graphql } from '$houdini';

	const { data, loading } = query(graphql`
		query Products {
			products {
				edges {
					node {
						name
					}
				}
			}
		}
	`);
</script>

{#if  $loading}
    loading...
{:else} 
    <ul>
 	{#each $data.products.edges as product}
		<li>{product.node.name}</li>
	{/each}
    </ul>
{/if}
```

By the way, if you haven't done it yet, I recommend walking through the [Getting Started series](https://www.houdinigraphql.com/intro/welcome)  which should explain how to best use Houdini+SvelteKit

**Comment by jycouet** [comment]
Everything looks great.

What if you put:
```svelte
{#each $data?.products?.edges ?? [] as product}
	<li>{product.node.name}</li>
{/each}
```

Or log `{ JSON.strigify($data, null, 2) }` on your page?

**Comment by kris-re** [comment]
That was the missing part!

I'd like to `prerender` most part of the app including queries. `prerender` is now the default and adding a `cache` policy to the query results in the data popping up after page load like a network request. Is this normal?

This is the new query:

```js
	const { data } = query(graphql`
		query Products @cache(policy: CacheOrNetwork) {
			products {
				edges {
					node {
						name
					}
				}
			}
		}
	`);
```

**Comment by AlecAivazis** [comment]
The easiest way to have your routes rendered on the server is to put your queries inside of `src/routes/...` and use mostly fragments inside of `src/lib/....`. All of the queries inside of routes will be pre-rendered on the server

**Comment by kris-re** [comment]
I tried to rebuild that with `fragment`, but for whatever reason the type `Products` is unknown. Where do the types come from?

```
npx houdini generate
 Generating runtime...
 Encountered error in src/lib/components/Products.svelte
Unknown type "Products". Did you mean "Product", "ProductTag", or "ProductType"?
```

**src/lib/components/Products.svelte**
```svelte
<script>
	import { fragment, graphql } from '$houdini';

	export let products;

	const data = fragment(
		graphql`
			fragment ProductData on Products {
				edges {
					node {
						name
					}
				}
			}
		`,
		products
	);
</script>

<ul>
	{#each products.edges as product}
		<li>{product.node.name}</li>
	{/each}
</ul>
```

**src/routes/index.svelte**
```svelte
<script context="module">
	import { query, graphql } from '$houdini';
	import Products from '$lib/components/Products.svelte';

	const { data } = query(graphql`
		query Products {
			products {
				...ProductData
			}
		}
	`);
</script>

<Products data={$data.products} />
```

**Comment by AlecAivazis** [comment]
Does your api's schema have a type called Products? It looks like your query is used the connection pattern which leads me to believe the type might be called ProductConnections? One place to check is inside the `schema.graphql` file that was created when you started your project

**Comment by AlecAivazis** [comment]
That error means that the preprocessor did not handle a `graphql`. Does your `sourceGlob` value include the component you are working with?

**Comment by AlecAivazis** [comment]
Also, if you would rather have a more direct way of chatting, feel free to reach out on discord!

**Comment by kris-re** [comment]
I think so: `sourceGlob: 'src/**/*.{svelte,gql,graphql}'`

The error log says `at index.svelte:6:17`, but I don't know what the problem is there.

<img width="456" alt="Bildschirmfoto 2022-07-10 um 11 43 36" src="https://user-images.githubusercontent.com/82714642/178139552-d707d189-5f80-4f9f-8867-24a386c929b4.png">

**src/routes/index.svelte**
```svelte
<script context="module">
	import { query, graphql } from '$houdini';
	import Products from '$lib/components/Products.svelte';

	const { data } = query(graphql`
		query Products {
			products {
				...ProductData
			}
		}
	`);
</script>

<Products products={$data.products} />
```

**src/lib/components/Products.svelte**
```svelte
<script>
	import { fragment, graphql } from '$houdini';

	export let products;

	const data = fragment(
		graphql`
			fragment ProductData on RootQueryToProductConnection {
				edges {
					node {
						name
					}
				}
			}
		`,
		products
	);
</script>

<ul>
	{#each $data.edges as product}
		<li>{product.node.name}</li>
	{/each}
</ul>
```

I don't have time for chatting at the moment, but will join when possible. Thanks!

**Comment by AlecAivazis** [comment]
Very strange - is this project somewhere I can pull from? I'd love to dig a little deeper and see what's going on

**Comment by kris-re** [comment]
I sent you the archive of my project on Discord – there is no repo at the moment. Hope that helps!

**Comment by AlecAivazis** [comment]
Thanks for that! I was able to reproduce the issue, will report back when i have more info 👍

**Comment by AlecAivazis** [comment]
Okay, I figured out what's happening. Queries need to be in a normal script tag, not `context="module"`. If you update `src/routes/index.svelte` to look like this, you'll get passed your issue:

```
<script>
	import { query, graphql } from '$houdini';
	import Products from '$lib/components/Products.svelte';

	const { data } = query(graphql`
		query Products {
			products(where: { category: "banner-king.de" }) {
				...ProductData
			}
		}
	`);
</script>

<Products products={$data.products} />

<h1>Welcome to SvelteKit</h1>
<p>
	Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation
</p>
```

I am running into a problem with the latest kit release but at least it's not caused by your code.

**Comment by AlecAivazis** [comment]
Figured out what was going on. you have prerender's default set to true which apparently doesn't mesh well with how we drive the queries. Once I turn that off, your application renders just fine.

**Comment by kris-re** [comment]
Ah yes, thank you for the help and sorry for multiple topics in one issue.

Hopefully, I will have an opportunity to contribute in the future.
