### ISSUE TITLE
Houdini preprocess, cannot find operation type

### ISSUE THREAD

**Issue by Nukiloco** [HoudiniGraphql/houdini#399]
```
Error: Error while preprocessing C:/Users/user/Desktop/Nukiloco/Projects/Project/full/.svelte-kit/generated/root.svelte - Could not find operation type
    at queryProcessor (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/houdini@0.15.4/node_modules/houdini/build/preprocess-esm/index.js:66623:15)
    at runPipeline (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/houdini@0.15.4/node_modules/houdini/build/preprocess-esm/index.js:16:15)
    at async applyTransforms (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/houdini@0.15.4/node_modules/houdini/build/preprocess-esm/index.js:67126:5)
    at async markup (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/houdini@0.15.4/node_modules/houdini/build/preprocess-esm/index.js:67208:28)
    at async process_markup (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.mjs:32599:23)
    at async preprocess (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.mjs:32629:30)
    at async compileSvelte2 (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.49_svelte@3.49.0+vite@2.9.13/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:331:22)
    at async TransformContext.transform (file:///C:/Users/user/Desktop/Nukiloco/Projects/Project/full/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.49_svelte@3.49.0+vite@2.9.13/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1791:25)
    at async Object.transform (C:\Users\user\Desktop\Nukiloco\Projects\Project\full\node_modules\.pnpm\vite@2.9.13\node_modules\vite\dist\node\chunks\dep-80fe9c6b.js:39292:30)
    at async doTransform (C:\Users\user\Desktop\Nukiloco\Projects\Project\full\node_modules\.pnpm\vite@2.9.13\node_modules\vite\dist\node\chunks\dep-80fe9c6b.js:50012:29)
```

I'm not sure what this error means exactly. I just know it goes away if I take houdini out of the preprocess ``svelte.config.js``

``svelte.config.js``
```
import adapter from '@sveltejs/adapter-node'
import preprocess from 'svelte-preprocess'
import houdini from 'houdini/preprocess'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [preprocess(), houdini()],

	kit: {
		adapter: adapter(),
	}
}

export default config;
```

**Comment by Nukiloco** [comment]
Never mind it was because I changed folder names so the schemaPath couldn't find any gql files.
Though I guess a better error message would be nice?

**Comment by AlecAivazis** [comment]
Ah ha! Well i'm glad you got this sorted out. I"m not really sure how we could detect what was happening but i'll add this situation to #362 so we can track it 👍
