### ISSUE TITLE
Build issue with Vercel

### ISSUE THREAD

**Issue by PimTournaye** [HoudiniGraphql/houdini#471]
### Describe the bug

```
Cloning completed: 531.268ms
--
11:10:57.214 | Looking up build cache...
11:10:59.162 | Build cache downloaded [33.72 MB]: 1490.718ms
11:10:59.378 | Running "vercel build"
11:10:59.854 | Vercel CLI 28.1.0
11:11:00.171 | Detected `pnpm-lock.yaml` generated by pnpm 7...
11:11:00.186 | Installing dependencies...
11:11:00.745 | Lockfile is up to date, resolution step is skipped
11:11:00.983 | Packages: +733 -6
11:11:00.984 | +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
11:11:01.271 | Progress: resolved 0, reused 0, downloaded 1, added 0
11:11:02.273 | Progress: resolved 0, reused 0, downloaded 31, added 20
11:11:03.274 | Progress: resolved 0, reused 0, downloaded 96, added 87
11:11:04.286 | Progress: resolved 0, reused 0, downloaded 220, added 209
11:11:05.285 | Progress: resolved 0, reused 0, downloaded 327, added 319
11:11:06.288 | Progress: resolved 0, reused 0, downloaded 409, added 410
11:11:07.288 | Progress: resolved 0, reused 0, downloaded 507, added 509
11:11:08.292 | Progress: resolved 0, reused 0, downloaded 644, added 659
11:11:09.292 | Progress: resolved 0, reused 0, downloaded 708, added 732
11:11:09.531 | node_modules/@sveltejs/kit postinstall$ node svelte-kit.js sync
11:11:09.533 | node_modules/svelte-preprocess postinstall$ echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
11:11:09.556 | node_modules/svelte-preprocess postinstall: [svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
11:11:09.557 | node_modules/svelte-preprocess postinstall: Done
11:11:10.293 | Progress: resolved 0, reused 0, downloaded 709, added 733, done
11:11:10.348 | node_modules/@sveltejs/kit postinstall: Done
11:11:10.373 | node_modules/esbuild postinstall$ node install.js
11:11:10.450 | node_modules/esbuild postinstall: Done
11:11:10.710 |  
11:11:10.712 |  
11:11:10.712 | > portfolio@0.0.1 prepare /vercel/path0
11:11:10.712 | > pnpm run gen
11:11:10.712 |  
11:11:11.179 |  
11:11:11.179 | > portfolio@0.0.1 gen /vercel/path0
11:11:11.179 | > pnpm gen:houdini
11:11:11.179 |  
11:11:11.650 |  
11:11:11.650 | > portfolio@0.0.1 gen:houdini /vercel/path0
11:11:11.651 | > houdini generate
11:11:11.651 |  
11:11:11.655 | sh: /vercel/path0/node_modules/.bin/houdini: Permission denied
11:11:11.657 | ELIFECYCLE  Command failed with exit code 126.
11:11:11.664 | ELIFECYCLE  Command failed with exit code 1.
11:11:11.670 | ELIFECYCLE  Command failed with exit code 1.
11:11:11.683 | Error! Command "pnpm install" exited with 1
```

Cannot build with Vercel

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. Clone `https://github.com/PimTournaye/portfolio`
2. Link repo to Vercel
3. Try to deploy
4. Look at error log

### Expected behavior

A successful build and deployment via Vercel

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 7.17 GB / 15.92 GB
  Binaries:
    Node: 17.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65
    @sveltejs/kit: next => 1.0.0-next.428
    houdini: ^0.15.8 => 0.15.8
    svelte: ^3.44.0 => 3.46.4
    vite: ^3.0.3 => 3.0.3
```

### Additional context

I know that the MR for the new SvelteKit API is in the works, but I don't think this issue is linked to that.

**Comment by AlecAivazis** [comment]
Mind giving this a shot with the latest update? I  agree that whatever issue you were running into is not related but it'd be good to confirm this is still a problem. I'm trying to wrap my head around why this hasn't affect any one else 🤔

**Comment by PimTournaye** [comment]
Will do, currently migrating to 0.16. Having some issues running the dev server though (although that might have been me being too brash and throwing out KitQL when updating houdini this time). Will keep you updated

```
> vite dev

error when starting dev server:
TypeError: file.isDirectory is not a function
    at walk (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:163:14)
    at create_routes_and_nodes (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:212:3)
    at create_manifest_data (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:23:28)
    at Module.create (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/@sveltejs/kit/src/core/sync/sync.js:25:24)
    at update_manifest (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/@sveltejs/kit/src/vite/dev/index.js:58:35)
    at dev (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/@sveltejs/kit/src/vite/dev/index.js:200:8)
    at async Object.configureServer (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/@sveltejs/kit/src/vite/index.js:499:11)
    at async createServer (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:59167:28)
    at async CAC.<anonymous> (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/vite/dist/node/cli.js:699:24)    
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by jycouet** [comment]
Could you try again with `0.16.0-next.1` and let us know? 
Thx a lot

**Comment by PimTournaye** [comment]
```
> portfolio@0.0.1 dev C:\Users\pimto\Documents\Code\portfolio
> vite dev

🎩 Generating runtime...
❌ _enterList$i.apply is not a function
error when starting dev server:
Error: see above
    at Context.buildStart (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/houdini/build/vite-esm/index.js:158244:23)
    at async Promise.all (index 2)
    at async Object.buildStart (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35192:13)
    at async file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:59233:13    
    at async Server.httpServer.listen (file:///C:/Users/pimto/Documents/Code/portfolio/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:59248:17)
 ELIFECYCLE  Command failed with exit code 1.
 ```
 Running `"houdini": "^0.16.0-next.1"`. Vite is not very happy at the moment, but that might be due to switching from KitQL to only Houdini

**Comment by jycouet** [comment]
I cloned your repo, had a look and had the same issue as you 👍

A few things need to be fixed... (Mainly due to kitql update, sveltekit update, houdini update). _It's fun to be on the edge 🥳._
First, you don't need `KitQL` as you have a client-side use case, `Houdini` will be great.

I think that you should start from a fresh project with `"houdini": "^0.16.0-next.1"` and see how it goes.
What do you think?

**Comment by PimTournaye** [comment]
I'll give it shot, I've been using this repo to play with SvelteKit a lot, something like this was bound to happen :3
Thanks for giving things a shot on your end!

**Comment by PimTournaye** [comment]
With a new skeleton project built up, I still get the same error once I add the `+page,gql` file in my route. If that file is empty, it does work though. Any idea what I could be doing wrong? Anything Houdini was set up with `npx houdinit init`

**Comment by jycouet** [comment]
Could you clone this: https://github.com/HoudiniGraphql/houdini-16-next as a starter kit?
Let us know how it works.

**Comment by PimTournaye** [comment]
Sorry for dropping of the map for a bit, did some more testing. Everything builds fine with the latest next on macOS and Linux (thanks Vercel), but when trying to develop on Windows, any GraphQL requests get returned as undefined. Also, on WIndows I have to replace some `\` chars with normal slashes in `$houdini/runtime/lib/config.js` and `$houdini/runtime/lib/network.js` every time something regenerates.

So, whatever issues there was with Vercel seems to be gone, but developing on Windows seems to be difficult at the moment.

**Comment by jycouet** [comment]
Do you mind closing this vercel issue and opening a new one for windows issue?
To keep track of versioning & co?

Thx
